version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: medusa-backend:latest
    container_name: medusa-server
    restart: always
    environment:
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      PORT: 9000
      STORE_CORS: ${STORE_CORS}
      ADMIN_CORS: ${ADMIN_CORS}